<?php
namespace demo\demo;

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * 结构体定义
 */
class DemoInfo {
  static $_TSPEC;

  /**
   * @var int
   */
  public $demo_id = null;
  /**
   * @var string
   */
  public $demo_name = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'demo_id',
          'type' => TType::I64,
          ),
        2 => array(
          'var' => 'demo_name',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['demo_id'])) {
        $this->demo_id = $vals['demo_id'];
      }
      if (isset($vals['demo_name'])) {
        $this->demo_name = $vals['demo_name'];
      }
    }
  }

  public function getName() {
    return 'DemoInfo';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->demo_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->demo_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('DemoInfo');
    if ($this->demo_id !== null) {
      $xfer += $output->writeFieldBegin('demo_id', TType::I64, 1);
      $xfer += $output->writeI64($this->demo_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->demo_name !== null) {
      $xfer += $output->writeFieldBegin('demo_name', TType::STRING, 2);
      $xfer += $output->writeString($this->demo_name);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


